[workspace]

members = [
    "apps/userdata",
    "apps/social",
    "packages/rs-id-gen",
    "packages/rs-models",
    "packages/rs-rocket-cors",
    "packages/rs-rocket-catcher",
    "packages/rs-rocket-response"
]
